/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/draft': RouteRecordInfo<'/posts/draft', '/posts/draft', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/i18n': RouteRecordInfo<'/posts/i18n', '/posts/i18n', Record<never, never>, Record<never, never>>,
    '/posts/test': RouteRecordInfo<'/posts/test', '/posts/test', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy': RouteRecordInfo<'/posts/test - Copy', '/posts/test - Copy', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy (10)': RouteRecordInfo<'/posts/test - Copy (10)', '/posts/test - Copy (10)', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy (11)': RouteRecordInfo<'/posts/test - Copy (11)', '/posts/test - Copy (11)', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy (12)': RouteRecordInfo<'/posts/test - Copy (12)', '/posts/test - Copy (12)', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy (13)': RouteRecordInfo<'/posts/test - Copy (13)', '/posts/test - Copy (13)', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy (14)': RouteRecordInfo<'/posts/test - Copy (14)', '/posts/test - Copy (14)', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy (2)': RouteRecordInfo<'/posts/test - Copy (2)', '/posts/test - Copy (2)', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy (3)': RouteRecordInfo<'/posts/test - Copy (3)', '/posts/test - Copy (3)', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy (4)': RouteRecordInfo<'/posts/test - Copy (4)', '/posts/test - Copy (4)', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy (5)': RouteRecordInfo<'/posts/test - Copy (5)', '/posts/test - Copy (5)', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy (6)': RouteRecordInfo<'/posts/test - Copy (6)', '/posts/test - Copy (6)', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy (7)': RouteRecordInfo<'/posts/test - Copy (7)', '/posts/test - Copy (7)', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy (8)': RouteRecordInfo<'/posts/test - Copy (8)', '/posts/test - Copy (8)', Record<never, never>, Record<never, never>>,
    '/posts/test - Copy (9)': RouteRecordInfo<'/posts/test - Copy (9)', '/posts/test - Copy (9)', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
